[package]
name = "mega-evm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "The evm tailored for the MegaETH"

[lints]
workspace = true

[dependencies]
# alloy
alloy-evm.workspace = true
alloy-op-evm.workspace = true
alloy-primitives.workspace = true

# op
op-alloy-consensus.workspace = true
op-revm.workspace = true

# revm
revm.workspace = true

# misc
delegate.workspace = true
derive_more.workspace = true
serde = { workspace = true, features = ["derive"] }

[features]
std = ["revm/std"]
test-utils = []
