[package]
name = "mega-evm"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "The evm tailored for the MegaETH"

[lints]
workspace = true

[dependencies]
# alloy
alloy-consensus.workspace = true
alloy-eips.workspace = true
alloy-evm.workspace = true
alloy-op-evm.workspace = true
alloy-op-hardforks.workspace = true
alloy-primitives.workspace = true
op-alloy-consensus.workspace = true

# megaeth
salt.workspace = true

# revm
revm.workspace = true
op-revm = { workspace = true, features = ["dev", "serde"] }

# misc
auto_impl.workspace = true
bitflags = "2.6"
delegate.workspace = true
derive_more.workspace = true
serde = { workspace = true, features = ["derive"] }

[dev-dependencies]
mega-evm = { path = ".", features = ["test-utils"] }
revm-inspectors.workspace = true

[features]
default = ["std", "revm/default", "op-revm/default"]
std = ["revm/std", "op-revm/std"]
test-utils = []
