[package]
name = "mega-evme"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "MegaETH executable EVM"
default-run = "mega-evme"

[lints]
workspace = true

[[bin]]
name = "mega-evme"
path = "src/main.rs"

[dependencies]
# megaeth
mega-evm = { workspace = true, features = ["default", "test-utils"] }
mega-evm-v1_0_1 = { package = "mega-evm", git = "https://github.com/megaeth-labs/mega-evm.git", branch = "william/fix/v1.0.1-inspector", features = ["default", "test-utils"] }
state-test.workspace = true

# revm
revm-inspectors = { workspace = true, features = ["std"] }

# alloy
alloy-consensus = { workspace = true, features = ["serde"] }
alloy-eips.workspace = true
alloy-network.workspace = true
alloy-primitives.workspace = true
alloy-provider = { workspace = true, features = ["reqwest"] }
alloy-rpc-types-eth.workspace = true
alloy-rpc-types-trace.workspace = true
alloy-serde = { workspace = true, features = ["default"] }
alloy-sol-types.workspace = true
alloy-transport-http = { workspace = true, features = ["reqwest"] }

# op
op-alloy-consensus.workspace = true
op-alloy-network.workspace = true
op-alloy-rpc-types.workspace = true

# misc
clap = { workspace = true, features = ["default", "env"] }
reqwest = "0.12"
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["rt", "macros"] }
tracing.workspace = true
tracing-subscriber = { workspace = true, features = ["fmt", "env-filter", "std", "ansi"] }
