[package]
name = "mega-evme"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
homepage.workspace = true
repository.workspace = true
description = "MegaETH executable EVM"
default-run = "mega-evme"

[lints]
workspace = true

[[bin]]
name = "mega-evme"
path = "src/main.rs"

[dependencies]
# megaeth
mega-evm = { workspace = true, features = ["default"] }
state-test.workspace = true

# revm
revm-inspectors.workspace = true

# alloy
alloy-consensus = { workspace = true, features = ["serde"] }
alloy-primitives.workspace = true
alloy-rpc-types-trace.workspace = true
alloy-serde = { workspace = true, features = ["default"] }

# op
op-alloy-consensus.workspace = true

# misc
clap = { workspace = true, features = ["default"] }
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
