name: no_std support
on:
  workflow_call:
  workflow_dispatch:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci-checks:
    runs-on: ubuntu-24.04
    timeout-minutes: 30
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_CI }}
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT_CI }}
          repository: megaeth-labs/chain-ops
          sparse-checkout: .github/actions
          path: chain-ops

      - name: Configure Git credentials
        uses: ./chain-ops/.github/actions/git_config
        with:
          github_pat: ${{ secrets.PAT_CI }}

      - name: Install Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: Install RISC-V target
        run: |
          rustup target add riscv64imac-unknown-none-elf

      - name: Check for riscv64imac-unknown-none-elf target
        run: |
          cargo check -p mega-evm --target riscv64imac-unknown-none-elf --no-default-features

      - name: Check with std feature
        run: |
          cargo check -p mega-evm --features std
